spring.application.name=backend
# ===============================
# 1. KONFIGURASI DATABASE SUPABASE
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.noftdptxujlnsykxmdee
spring.datasource.password=!@#20Mr05Supabase#@!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# 2. KONFIGURASI EMAIL VERIFIKASI
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amokaybmx@gmail.com
spring.mail.password=fdevermhqshmqodg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# 3. KONFIGURASI APP / FRONTEND
# ===============================
# Ganti dengan IP WiFi laptop Anda saat ini
app.frontend.url=http://192.168.18.12:8080

# ===============================
# 4. UPLOAD FILE LIMIT
# ===============================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# ===============================
# 5. TIMEZONE KONFIGURASI
# ===============================
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta

server.port=${PORT:8080}